### ISSUE TITLE
Schematic and Board Documentation not synced

### ISSUE THREAD

**Issue by nilavghosh** [spacelab-ufsc/ttc#16]
Hi Team,
Thanks for some brilliant work on building and sharing an open source cubesat.

I was studying your TTC and I think the documentation and the hardware schematic are not synced. Would be great if you can help confirm if this is so. I have looked at the v1.0 and v1.1 versions and see the same. Attaching screenshots below,

![image](https://github.com/spacelab-ufsc/ttc/assets/657155/a840fb19-14d3-4cbb-9d80-cdce510ac43a)
![image](https://github.com/spacelab-ufsc/ttc/assets/657155/5d9f8b8a-586c-4109-a858-48afe6a5a21d)

Regards,
Nilav

**Comment by nilavghosh** [comment]
Hello @miguelboing @mgm8  . Just circling back to check :). If you can confirm the doc and the boards are out of sync that should be ok as well.

**Comment by mgm8** [comment]
Hello @nilavghosh,

The documentation is outdated, the correct version of the PC104 pinout is the version presented in the schematics.

Thanks for findout the issue.

**Comment by nilavghosh** [comment]
Thanks @mgm8 . Appreciate the response. Is there a newer version of the document? If not . I'll treat the schematic as the source of truth. Thanks .
