### ISSUE TITLE
Hardware: Update the standard of the Altium project according to the new standard

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc#9]
PCB standard: [https://github.com/spacelab-ufsc/pcb-standard](https://github.com/spacelab-ufsc/pcb-standard)

**Comment by YanAzer** [comment]
@mgm8 this issue is the same as https://github.com/spacelab-ufsc/ttc/issues/1

**Comment by mgm8** [comment]
@YanAzer maked as [duplicate](https://github.com/spacelab-ufsc/ttc/labels/duplicate)
